SNAPTX-4358 [SsmConfig] Gem Inconsistent Behavior for Values which exists in File as well as DB
bodyshopbidsdotcom/ssm_config pull request #21
Opened 2024-09-23 14:57 UTC by holmes2

Closes https://snapsheettech.atlassian.net/browse/SNAPTX-4358

2024-09-23 15:16 UTC, holmes2 commented
Addresses this issue: https://github.com/bodyshopbidsdotcom/ssm_config/issues/18

2024-09-27 19:21 UTC, uttercm requested changes
I pointed TX to this branch for the ssmconfig gem and am receiving this error
```
➜ rails c                                          
WARN: Unresolved or ambiguous specs during Gem::Specification.reset:
      minitest (>= 5.1)
      Available/installed versions of this gem:
      - 5.20.0
      - 5.13.0
WARN: Clearing out unresolved specs. Try 'gem cleanup <gem>'
Please report a bug if this causes problems.
/Users/carrieutter/.rvm/rubies/ruby-2.7.8/lib/ruby/2.7.0/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError
/Users/carrieutter/.rvm/gems/ruby-2.7.8@snapsheet-tx/gems/net-protocol-0.2.2/lib/net/protocol.rb:68: warning: previous definition of ProtocRetryError was here
/Users/carrieutter/.rvm/rubies/ruby-2.7.8/lib/ruby/2.7.0/net/protocol.rb:206: warning: already initialized constant Net::BufferedIO::BUFSIZE
/Users/carrieutter/.rvm/gems/ruby-2.7.8@snapsheet-tx/gems/net-protocol-0.2.2/lib/net/protocol.rb:214: warning: previous definition of BUFSIZE was here
/Users/carrieutter/.rvm/rubies/ruby-2.7.8/lib/ruby/2.7.0/net/protocol.rb:503: warning: already initialized constant Net::NetPrivate::Socket
/Users/carrieutter/.rvm/gems/ruby-2.7.8@snapsheet-tx/gems/net-protocol-0.2.2/lib/net/protocol.rb:541: warning: previous definition of Socket was here
WARNING: Skipping key "RAILS_ENV". Already set in ENV.
WARNING: Use strings for Figaro configuration. 1234567890 was converted to "1234567890".
WARNING: MYSQL_OPT_RECONNECT is deprecated and will be removed in a future version.
Traceback (most recent call last):
	55: from bin/rails:5:in `<main>'
	54: from /Users/carrieutter/.rvm/gems/ruby-2.7.8@snapsheet-tx/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	53: from /Users/carrieutter/.rvm/gems/ruby-2.7.8@snapsheet-tx/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	52: from /Users/carrieutter/.rvm/gems/ruby-2.7.8@snapsheet-tx/gems/railties-6.1.7.6/lib/rails/commands.rb:18:in `<main>'
	51: from /Users/carrieutter/.rvm/gems/ruby-2.7.8@snapsheet-tx/gems/railties-6.1.7.6/lib/rails/command.rb:48:in `invoke'
	50: from /Users/carrieutter/.rvm/gems/ruby-2.7.8@snapsheet-tx/gems/railties-6.1.7.6/lib/rails/command/base.rb:69:in `perform'
	49: from /Users/carrieutter/.rvm/gems/ruby-2.7.8@snapsheet-tx/gems/thor-1.3.0/lib/thor.rb:527:in `dispatch'
	48: from /Users/carrieutter/.rvm/gems/ruby-2.7.8@snapsheet-tx/gems/thor-1.3.0/lib/thor/invocation.rb:127:in `invoke_command'
	47: from /Users/carrieutter/.rvm/gems/ruby-2.7.8@snapsheet-tx/gems/thor-1.3.0/lib/thor/command.rb:28:in `run'
	46: from /Users/carrieutter/.rvm/gems/ruby-2.7.8@snapsheet-tx/gems/railties-6.1.7.6/lib/rails/commands/console/console_command.rb:101:in `perform'
	45: from /Users/carrieutter/.rvm/gems/ruby-2.7.8@snapsheet-tx/gems/railties-6.1.7.6/lib/rails/command/actions.rb:15:in `require_application_and_environment!'
	44: from /Users/carrieutter/.rvm/gems/ruby-2.7.8@snapsheet-tx/gems/railties-6.1.7.6/lib/rails/command/actions.rb:28:in `require_environment!'
	43: from /Users/carrieutter/.rvm/gems/ruby-2.7.8@snapsheet-tx/gems/railties-6.1.7.6/lib/rails/application.rb:367:in `require_environment!'
	42: from /Users/carrieutter/.rvm/gems/ruby-2.7.8@snapsheet-tx/gems/activesupport-6.1.7.6/lib/active_support/dependencies.rb:332:in `require'
	41: from /Users/carrieutter/.rvm/gems/ruby-2.7.8@snapsheet-tx/gems/activesupport-6.1.7.6/lib/active_support/dependencies.rb:299:in `load_dependency'
	40: from /Users/carrieutter/.rvm/gems/ruby-2.7.8@snapsheet-tx/gems/activesupport-6.1.7.6/lib/active_support/dependencies.rb:332:in `block in require'
	39: from /Users/carrieutter/.rvm/gems/ruby-2.7.8@snapsheet-tx/gems/zeitwerk-2.6.12/lib/zeitwerk/kernel.rb:38:in `require'
	38: from /Users/carrieutter/.rvm/gems/ruby-2.7.8@snapsheet-tx/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	37: from /Users/carrieutter/.rvm/gems/ruby-2.7.8@snapsheet-tx/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	36: from /Users/carrieutter/Documents/snapsheet-tx/config/environment.rb:5:in `<main>'
	35: from /Users/carrieutter/.rvm/gems/ruby-2.7.8@snapsheet-tx/gems/railties-6.1.7.6/lib/rails/application.rb:391:in `initialize!'
	34: from /Users/carrieutter/.rvm/gems/ruby-2.7.8@snapsheet-tx/gems/railties-6.1.7.6/lib/rails/initializable.rb:60:in `run_initializers'
	33: from /Users/carrieutter/.rvm/rubies/ruby-2.7.8/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
	32: from /Users/carrieutter/.rvm/rubies/ruby-2.7.8/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
	31: from /Users/carrieutter/.rvm/rubies/ruby-2.7.8/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
	30: from /Users/carrieutter/.rvm/rubies/ruby-2.7.8/lib/ruby/2.7.0/tsort.rb:347:in `call'
	29: from /Users/carrieutter/.rvm/rubies/ruby-2.7.8/lib/ruby/2.7.0/tsort.rb:347:in `each'
	28: from /Users/carrieutter/.rvm/rubies/ruby-2.7.8/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
	27: from /Users/carrieutter/.rvm/rubies/ruby-2.7.8/lib/ruby/2.7.0/tsort.rb:415:in `each_strongly_connected_component_from'
	26: from /Users/carrieutter/.rvm/rubies/ruby-2.7.8/lib/ruby/2.7.0/tsort.rb:415:in `call'
	25: from /Users/carrieutter/.rvm/gems/ruby-2.7.8@snapsheet-tx/gems/railties-6.1.7.6/lib/rails/initializable.rb:50:in `tsort_each_child'
	24: from /Users/carrieutter/.rvm/gems/ruby-2.7.8@snapsheet-tx/gems/railties-6.1.7.6/lib/rails/initializable.rb:50:in `each'
	23: from /Users/carrieutter/.rvm/rubies/ruby-2.7.8/lib/ruby/2.7.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	22: from /Users/carrieutter/.rvm/rubies/ruby-2.7.8/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
	21: from /Users/carrieutter/.rvm/rubies/ruby-2.7.8/lib/ruby/2.7.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	20: from /Users/carrieutter/.rvm/rubies/ruby-2.7.8/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	19: from /Users/carrieutter/.rvm/rubies/ruby-2.7.8/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
	18: from /Users/carrieutter/.rvm/gems/ruby-2.7.8@snapsheet-tx/gems/railties-6.1.7.6/lib/rails/initializable.rb:61:in `block in run_initializers'
	17: from /Users/carrieutter/.rvm/gems/ruby-2.7.8@snapsheet-tx/gems/railties-6.1.7.6/lib/rails/initializable.rb:32:in `run'
	16: from /Users/carrieutter/.rvm/gems/ruby-2.7.8@snapsheet-tx/gems/railties-6.1.7.6/lib/rails/initializable.rb:32:in `instance_exec'
	15: from /Users/carrieutter/.rvm/gems/ruby-2.7.8@snapsheet-tx/gems/railties-6.1.7.6/lib/rails/engine.rb:633:in `block in <class:Engine>'
	14: from /Users/carrieutter/.rvm/gems/ruby-2.7.8@snapsheet-tx/gems/railties-6.1.7.6/lib/rails/engine.rb:633:in `each'
	13: from /Users/carrieutter/.rvm/gems/ruby-2.7.8@snapsheet-tx/gems/railties-6.1.7.6/lib/rails/engine.rb:634:in `block (2 levels) in <class:Engine>'
	12: from /Users/carrieutter/.rvm/gems/ruby-2.7.8@snapsheet-tx/gems/railties-6.1.7.6/lib/rails/engine.rb:680:in `load_config_initializer'
	11: from /Users/carrieutter/.rvm/gems/ruby-2.7.8@snapsheet-tx/gems/activesupport-6.1.7.6/lib/active_support/notifications.rb:205:in `instrument'
	10: from /Users/carrieutter/.rvm/gems/ruby-2.7.8@snapsheet-tx/gems/railties-6.1.7.6/lib/rails/engine.rb:681:in `block in load_config_initializer'
	 9: from /Users/carrieutter/.rvm/gems/ruby-2.7.8@snapsheet-tx/gems/activesupport-6.1.7.6/lib/active_support/dependencies.rb:326:in `load'
	 8: from /Users/carrieutter/.rvm/gems/ruby-2.7.8@snapsheet-tx/gems/activesupport-6.1.7.6/lib/active_support/dependencies.rb:299:in `load_dependency'
	 7: from /Users/carrieutter/.rvm/gems/ruby-2.7.8@snapsheet-tx/gems/activesupport-6.1.7.6/lib/active_support/dependencies.rb:326:in `block in load'
	 6: from /Users/carrieutter/.rvm/gems/ruby-2.7.8@snapsheet-tx/gems/activesupport-6.1.7.6/lib/active_support/dependencies.rb:326:in `load'
	 5:  [...]

2024-09-30 14:32 UTC, uttercm approved these changes
CR: LG
FR: verified that the SsmConfig always calls the db even before any other query is run

2024-10-01 16:30 UTC, w1nniejao approved these changes
CR: LG
FR: Priyank walked through the test with me and it works

2024-10-01 16:32 UTC, merged